#!/usr/bin/env python
import argparse
import sys
import subprocess
import os.path

parser = argparse.ArgumentParser(description='Installer script for the octave environment.')

# Replace the default rand() function with our implementation to make the results consistent
# with MATLAB and others

if sys.platform == 'darwin':
    exec_path = '/Applications/Octave.app/Contents/Resources/usr/bin/mkoctfile'
    lib_dir = 'osx'
elif sys.platform.startswith('linux'):
    try:
        exec_path = subprocess.Popen(["which", "mkoctfile"], stdout=subprocess.PIPE).communicate()[0][:-1]
    except subprocess.CalledProcessError as e:
        print "Could not retrieve path of mkoctfile"
        print e
        sys.exit(e.returncode)

    lib_dir = 'linux'
else:
    print 'Not supported.'
    sys.exit(99)

env_dir = os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(os.path.realpath(__file__))), lib_dir))
function_name = 'ostrich_rand'
c_file_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), './ostrich_twister_rand_mex.c')

if not os.path.isfile(exec_path):
    print 'Could not find ' + str(exec_path)
    sys.exit(1)
else:
    print 'Found mkoctfile in ' + exec_path

try:
	subprocess.check_call(
		[exec_path, 
            c_file_path,
            '--mex',
            '-o',
			os.path.join(env_dir, function_name),
		], stdout=sys.stdout, stderr=sys.stderr)
	print 'Successfully compiled mex function'
	sys.exit(0)
except subprocess.CalledProcessError as e:
	print e
	sys.exit(e.returncode)











